# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 16:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codequiz', '0002_auto_20151222_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codequiz',
            name='test_cases',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
