# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequiz', '0003_auto_20151222_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codequiz',
            name='bootstrap_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='codequiz',
            name='problem_statement',
            field=models.TextField(blank=True, default=''),
        ),
    ]
