# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 13:39
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codequiz', '0004_auto_20151222_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_key', models.CharField(db_index=True, max_length=40)),
                ('state', models.IntegerField(choices=[(0, 'NOT_EVALUATED'), (1, 'EVALUATING'), (2, 'EVALUATED'), (3, 'EVALUATION_FAILED')], default=0)),
                ('code', models.TextField()),
                ('result', models.BooleanField(default=False)),
                ('test_cases_results', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField()),
                ('codequiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codequiz.CodeQuiz')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='codequizattempt',
            unique_together=set([('codequiz', 'user_key', 'code')]),
        ),
    ]
