# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequiz', '0005_auto_20151223_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codequizattempt',
            old_name='test_cases_results',
            new_name='response',
        ),
        migrations.AlterField(
            model_name='codequizattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
