# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codequiz', '0006_auto_20151223_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codequizattempt',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
