# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequiz', '0007_auto_20151223_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codequizattempt',
            name='code',
            field=models.TextField(db_index=True),
        ),
    ]
