# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codequiz', '0008_auto_20160111_1759'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codequizattempt',
            unique_together=set([]),
        ),
    ]
