# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='where_to_go_from_here',
            field=models.TextField(default=''),
        ),
    ]
