# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20160103_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='how_to_learn',
            field=models.TextField(default=''),
        ),
    ]
