# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_display',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_display',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
