# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20160106_0933'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='attempt_number',
        ),
    ]
